name: Pack and Release

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '1.0.0-dev'
      prerelease:
        description: 'This is a pre-release'
        required: true
        default: 'true'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: set version from release
      run: |
        echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        echo "PRE_RELEASE=${{ github.event.release.prerelease }}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Restore dependencies
      run: dotnet restore ./src/

    - name: Build
      run: dotnet build ./src/ --no-restore --configuration release -p:Version=${{env.VERSION}}

    - name: Test
      run: dotnet test ./src/ --configuration release --no-build -p:Version=${{env.VERSION}}

    - name: Pack
      run: dotnet pack ./src/ --configuration release --no-build -p:Version=${{env.VERSION}} --output . 

    - name: Push
      run: dotnet nuget push ./*.${{env.VERSION}}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
    
